use_frameworks!

platform :ios, '8.0'

target 'GCPopMenuView_Example' do
  pod 'GCPopMenuView', :path => '../'

  target 'GCPopMenuView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
